# Generated by Django 4.2.5 on 2023-11-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_liketoquestion_liketoanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionToAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('+', 'like'), ('-', 'dislike')], max_length=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.answer')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionToQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('+', 'like'), ('-', 'dislike')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='liketoquestion',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='liketoquestion',
            name='question',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/image/default_ava.png', null=True, upload_to='uploads'),
        ),
        migrations.DeleteModel(
            name='LikeToAnswer',
        ),
        migrations.DeleteModel(
            name='LikeToQuestion',
        ),
        migrations.AddField(
            model_name='reactiontoquestion',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_to_questions', to='app.profile'),
        ),
        migrations.AddField(
            model_name='reactiontoquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app.question'),
        ),
        migrations.AddField(
            model_name='reactiontoanswer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_to_answers', to='app.profile'),
        ),
    ]
