# Generated by Django 4.2.5 on 2023-11-15 19:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reactiontoanswer_reactiontoquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
